// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBWavrgWYWUXHaftV60AQQNPMk412kssQ',
    appId: '1:815027227715:web:f88cab05b877616b3dd8f6',
    messagingSenderId: '815027227715',
    projectId: 'flash-chat-90cbf',
    authDomain: 'flash-chat-90cbf.firebaseapp.com',
    storageBucket: 'flash-chat-90cbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tKAF8NdmenyxvTBQufsp4H53LgrxfaQ',
    appId: '1:815027227715:android:d86e039c6783ced13dd8f6',
    messagingSenderId: '815027227715',
    projectId: 'flash-chat-90cbf',
    storageBucket: 'flash-chat-90cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkE2u0nvXJCO40axD4qYgyOyGG5405xpI',
    appId: '1:815027227715:ios:263949bbef8a20983dd8f6',
    messagingSenderId: '815027227715',
    projectId: 'flash-chat-90cbf',
    storageBucket: 'flash-chat-90cbf.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkE2u0nvXJCO40axD4qYgyOyGG5405xpI',
    appId: '1:815027227715:ios:263949bbef8a20983dd8f6',
    messagingSenderId: '815027227715',
    projectId: 'flash-chat-90cbf',
    storageBucket: 'flash-chat-90cbf.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBWavrgWYWUXHaftV60AQQNPMk412kssQ',
    appId: '1:815027227715:web:24187558264b64103dd8f6',
    messagingSenderId: '815027227715',
    projectId: 'flash-chat-90cbf',
    authDomain: 'flash-chat-90cbf.firebaseapp.com',
    storageBucket: 'flash-chat-90cbf.firebasestorage.app',
  );
}
